
# train and val data as 1) directory: path/images/, 2) file: path/images.txt, or 3) list: [path1/images/, path2/images/]
train: D:\JeffW\Data\DefectBoxDetection\17_4JS1\train.txt
val: D:\JeffW\Data\DefectBoxDetection\17_4JS1\valid.txt

# number of classes
nc: 1

# class names
names: [ 'FM_Black' ]